### ISSUE TITLE
API base structure

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#12]
### Description
The REST API should be easily extendible with a already existing fundament

### Tasks
- [x] Create a DAO fundament
- [x] Create the API endpoints
- [x] Create the API interfaces

### Constraintes
This ticket will not cover any logic
