### ISSUE TITLE
Enable CSRF protection

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#13]
### Description
It is crucial to enable Cross-Site Request Forgery (CSRF) protection. CSRF attacks exploit the trust a website has in a user's browser, tricking the browser into sending unauthorized requests on behalf of the user. This can lead to unintended actions like data modification or unauthorized access.

### Tasks

- [ ] Enable CSRF Protection in Spring Security:
- [ ] Include CSRF Token in Forms
- [ ] Validate CSRF Tokens on the Server:

### Constraints
This ticket only includes the CSRF protection and no other security mechanism yet
