### ISSUE TITLE
Integrate OpenAPI into service

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#14]
### Description
The API should be well documented and there should be a generation basis for the webapp

### Tasks

- [x] Integrate OpenAPI into Spring Boot Service
- [x] Create basis for webapp to generate service sources
- [x] Test it out manually

### Constraints
This ticket will only consider the documentation and no specific implementation of models or API
