### ISSUE TITLE
Sundowner Service: Implement spot retrieving

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#15]
### Description
This is the service part of the feature **ACR2000**

The idea is that the current central spot of the screen of the user will be sent to the backend. The Spring service will retrieve the nearest places (max 10) and will sent them back to the user. There it will be marked again. The zoom level and the current viewport have to be considered. If there are more than 10 spots fitting the criteria the spots with the most reviews will be shown.

### Tasks

- [x] Create API endpoint for getting the points
- [x] Create TO for the user
- [ ] Write serialization tests for the TOs
- [ ] Implement the service function with the told criteria
- [ ] Write integration tests

### Constraints
This ticket will only cover the service part of the feature **ACR2000**. The webapp part will be handled seperately.
