### ISSUE TITLE
Sundowner Webapp - Implement Spot Retrieving

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#16]
### Description
This is the webapp part of the feature **ACR2000**.  

It should be possible that when panning of the map ends spots are loaded into the map. ~~It should be differentiated between mobile and desktop (Mobile - 8, Desktop - 10).~~

### Tasks
- [x] Implement calling the fetch method after panning.
- [x] Implement removing markers after panning
- [ ] ~~Implement differentiation mechanism of mobile and desktop~~
- [x] Load test spots into the database and make a function test
- [x] Make adjustments for better UX if needed or a new isssue
- [ ] #22
