### ISSUE TITLE
GUI-Test pipeline

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#17]
### Description
GUI-Tests are not possible yet. There should be a test base for GUI-Tests

### Tasks
- [ ] Install selenium (or maybe another GUI-Test framework)
- [ ] Implement Test classes
- [ ] Wage using more than 2 browsers for testing

### Additional Information
Maybe use the issue #16  as testing ground
