### ISSUE TITLE
Enable CORS 

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#18]
### Description
CORS should be enabled for the webapp to access to server. Also Spring security should be introduced as well

### Tasks
- [x] Enable CORS for ~~development~~
- [ ] ~~Enable CORS for production~~
- [x] Enable Spring security

### Constraints
Important for  #16
