### ISSUE TITLE
WebApp - Custom spot marker 

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#20]
### Description
The spot marker should show the Info provided by MapSpotTO

### Tasks
- [x] Create spot marker component
- [x] Display the info of the marker
- [x] Make it beautiful
