### ISSUE TITLE
Leaflet - Configure map to hide irrelevant spots

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#21]
### Description
The map is stuffed and should hide irrelevant spots.

### Tasks
- [ ] Determine irrelevant spots
- [ ] Find out how to hide them
- [ ] Implement the hiding configuration

**Comment by tkoeppel** [comment]
With the use of Jawg dark tile provider unimportant spots are already hidden

**Comment by tkoeppel** [comment]
Duplicate of #30
