### ISSUE TITLE
Webapp - Popup Menu see spot details

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#23]
### Description
After clicking an icon a menu should show up 

### Tasks
- [ ] The map should be centered around popup
- [ ] The popup should contain buttons to add a review
- [ ] The popup should contain a small button to flag impropiate

### Contstraints
This ticket will dependent on the spot and photo API
