### ISSUE TITLE
Service - Get photos of a spot

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#25]
### Description
When triggering the spot popup some photos should be shown in lower quality for display

### Tasks
- [ ] New API method for fetching photos. Maybe lazy loading with 5 at a time (tbd)
- [ ] Add likes to photo in DB object
- [ ] Order photos in best rated to worst
- [ ] Photos should not be original quality but lowered down

### Constraints
This ticket only handles many photos with low quality at once. The photo view with HQ will be handled by a seperate ticket
