### ISSUE TITLE
Security mechanism for not triggerin events too much

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#26]
### Description
Because this website does not handle accounts a security mechanism should be implemented to not activat things several times

### Tasks
- [ ] Recherche to maybe change to real user handling. The fronteer to make an account shoul be minimal and data should be safe
- [ ] Recherche for pseudo user handling
- [ ] Recherche to security mechanism when no accounts
- [ ] Make a followup ticket for implementation
- [ ] Dcument the results

### Constraints
This ticket is only a clear up action how to proceed. The implementation tasks will be handled seperately
