### ISSUE TITLE
WebApp - Optimize mapspot fetching

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#28]
### Description
Currently, we fetch map spots whenever the user pans the map. This can lead to performance issues and unnecessary data fetching. We need to implement a mechanism to fetch spots only when the user has stopped panning for a short period and only for the newly visible map area.
### Tasks:
- [x]  Determine the optimal debounce time for fetching new spots after the map stops moving.
- [x]  Modify the spot fetching logic to only fetch spots within the newly visible map area.
- [x]  Cache the already loaded spots to prevent reloading (former #27)
