### ISSUE TITLE
Restructuring project 

### ISSUE THREAD

**Issue by tkoeppel** [tkoeppel/sundowner#9]
### Description
The project should be well structured and organised. The testing should work.

### Tasks
- [x] Restrcuture the integrationtest and data into seperate projects under the sundowner-service
- [x] Rewrite the gradle.build.kts for every project
- [x] Make sure the testing works
